jars : controlserver.jar chaintools.jar reighley.jar focus_game.jar

controlserver.jar : ../scala/controlserver.jar
	cp ../scala/controlserver.jar .

../scala/controlserver.jar : 
	cd ../scala
	make controlserver.jar
